# Generated by Django 4.0.1 on 2022-01-10 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('school_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_name', models.CharField(max_length=170, verbose_name='Название теста')),
                ('i_number_of_questions', models.IntegerField(verbose_name='Количесто вопросов')),
                ('i_score_to_pass', models.IntegerField(verbose_name='% для прохождения')),
                ('vc_difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('extra-hard', 'extra-hard')], max_length=15)),
                ('i_xp', models.IntegerField()),
                ('vc_quiz_repr', models.CharField(choices=[('match', 'match'), ('true/false', 'true/false'), ('open_question', 'open_question'), ('general', 'general')], max_length=20)),
                ('i_lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='К какому уроку относится')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Тесты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_users.userprofile', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created_at', models.DateTimeField(default=datetime.datetime(2022, 1, 10, 17, 44, 15, 521072, tzinfo=utc))),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('correct', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('extra-hard', 'extra-hard')], max_length=15)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Вопрос')),
            ],
        ),
    ]
