# Generated by Django 4.0.1 on 2022-01-10 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='i_xp',
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_xp_for_test',
            field=models.IntegerField(default=15, verbose_name='Максимальный опыт за тест'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('extra-hard', 'extra-hard')], default='easy', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='dt_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 18, 38, 17, 294050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='i_number_of_questions',
            field=models.IntegerField(verbose_name='Количество вопросов'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='vc_difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('extra-hard', 'extra-hard')], max_length=15, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='vc_quiz_repr',
            field=models.CharField(choices=[('match', 'match'), ('true/false', 'true/false'), ('open_question', 'open_question'), ('general', 'general')], max_length=20, verbose_name='Представление теста'),
        ),
    ]
