# Generated by Django 4.0.1 on 2022-01-10 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_i_xp_quiz_max_xp_for_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('extra-hard', 'extra-hard')], default='easy', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='dt_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 18, 41, 52, 439141, tzinfo=utc)),
        ),
    ]
