# Generated by Django 4.0.1 on 2022-01-10 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_answer_difficulty_question_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='max_xp_for_test',
        ),
        migrations.AddField(
            model_name='question',
            name='xp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('grammar', 'grammar'), ('listening', 'listening'), ('reading', 'reading'), ('use_of_english', 'use_of_english'), ('writing', 'writing')], default='grammar', max_length=20, verbose_name='Тип теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dt_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 19, 15, 3, 408470, tzinfo=utc)),
        ),
    ]
