# Generated by Django 4.0.1 on 2022-01-10 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_max_xp_for_test_question_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='i_number_of_questions',
        ),
        migrations.AlterField(
            model_name='question',
            name='dt_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 19, 17, 46, 313980, tzinfo=utc)),
        ),
    ]
