# Generated by Django 4.0.1 on 2022-01-11 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_i_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dt_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='vc_quiz_repr',
            field=models.CharField(choices=[('match', 'match'), ('true/false', 'true/false'), ('open_question', 'open_question'), ('general', 'general'), ('space_word', 'space_word')], max_length=20, verbose_name='Представление теста'),
        ),
    ]
