# Generated by Django 4.0.1 on 2022-01-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_users', '0002_alter_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ch_name', models.CharField(max_length=130)),
                ('ch_description', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ch_name', models.CharField(max_length=100)),
                ('ch_description', models.CharField(max_length=800)),
                ('fl_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_subscription_start', models.DateTimeField()),
                ('dt_subscription_end', models.DateTimeField()),
                ('i_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo')),
                ('i_subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subscriptiontype')),
                ('i_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_users.userprofile')),
            ],
        ),
    ]
