# Generated by Django 4.0.1 on 2022-01-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_userranking_xp_userranking_i_xp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userranking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.usercourses'),
        ),
    ]
