# Generated by Django 4.0.1 on 2022-01-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('ch_password', models.CharField(max_length=60, verbose_name='password')),
                ('b_is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('ch_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('ch_surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('url_photo', models.URLField(max_length=250, verbose_name='Photo')),
                ('dt_register_date', models.DateTimeField(verbose_name='Дата регистрации')),
                ('dt_total_time_on_the_website', models.FloatField(verbose_name='Всего времени на вебсайте')),
                ('i_confirmation_links_amount', models.IntegerField(default=1)),
                ('xp', models.FloatField()),
                ('courses_access_json', models.JSONField()),
            ],
        ),
    ]
