# Generated by Django 4.0.1 on 2022-01-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dt_total_time_on_the_website',
        ),
    ]
