# Generated by Django 4.0.1 on 2022-01-10 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0002_remove_userprofile_dt_total_time_on_the_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dt_register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 19, 26, 34, 180340, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
    ]
