# Generated by Django 4.0.1 on 2022-01-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0003_alter_userauth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_metrics_type', models.IntegerField()),
                ('ch_metrics_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_users.metricstype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_users.userprofile')),
            ],
        ),
    ]
