# Generated by Django 4.0.1 on 2022-01-11 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0003_alter_userprofile_dt_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dt_register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
    ]
