# Generated by Django 4.0.1 on 2022-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0004_metricstype_usermetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='is_active',
            new_name='b_is_active',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='password',
            new_name='ch_password',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='username',
            new_name='ch_username',
        ),
        migrations.RenameField(
            model_name='usermetrics',
            old_name='metrics_type',
            new_name='i_metrics_type',
        ),
        migrations.RenameField(
            model_name='usermetrics',
            old_name='user_id',
            new_name='i_user_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='ch_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='surname',
            new_name='ch_surname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='register_date',
            new_name='dt_register_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_time_on_the_website',
            new_name='dt_total_time_on_the_website',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='i_user_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='url_photo',
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='i_metrics_value',
            field=models.IntegerField(default=1),
        ),
    ]
