# Generated by Django 4.0.1 on 2022-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0005_rename_is_active_userauth_b_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='ch_password',
            field=models.CharField(max_length=40),
        ),
    ]
