# Generated by Django 4.0.1 on 2022-01-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_userranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=150)),
                ('lesson_text', models.CharField(max_length=3000)),
                ('lesson_plan', models.CharField(max_length=1500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson_video')),
            ],
        ),
    ]
