# Generated by Django 4.0.1 on 2022-01-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='ch_lesson_name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_plan',
            new_name='ch_lesson_plan',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_text',
            new_name='ch_lesson_text',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='i_course_id',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video',
            new_name='i_video',
        ),
        migrations.RenameField(
            model_name='lesson_video',
            old_name='video_link',
            new_name='ch_video_link',
        ),
        migrations.RenameField(
            model_name='lesson_video',
            old_name='video_name',
            new_name='ch_video_name',
        ),
    ]
